name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #
  # golangci-lint
  #
  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.17.5]
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          args: --timeout=5m
          skip-go-installation: true

  tests-mac-os:
    name: MacOS unit tests
    runs-on: macos-10.15
    timeout-minutes: 10
    needs: [linters]
    env:
      GOTEST: gotestsum --

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - uses: actions/checkout@v2
      - run: sudo -E PATH=$PATH script/setup/install-gotestsum
      - name: Tests
        env:
          GOPROXY: direct
          GOTESTSUM_JUNITFILE: "${{ github.workspace }}/macos-test-junit.xml"
        run: make test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: TestResults MacOS
          path: |
            *-junit.xml
